---
- name: Testing the pharmacy application
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    base_url: "http://127.0.0.1:5000"

  tasks:

    - name: Test responsiveness
      ansible.builtin.uri:
        url: "{{ base_url }}/"
        method: GET
      register: responsiveness_results

    - name: Display responsiveness results
      ansible.builtin.debug:
        var: responsiveness_results

    - name: Check inventory
      ansible.builtin.uri:
        url: "{{ base_url }}/view_inventory"
        method: GET
      register: inventory_results

    - name: Display inventory results
      ansible.builtin.debug:
        var: inventory_results

    - name: Get customer details
      ansible.builtin.uri:
        url: "{{ base_url }}/view_customer/{{ item }}"
        method: GET
      register: customer_details_results
      loop:
        - customer_id_1
        - customer_id_2

    - name: Display customer details results
      ansible.builtin.debug:
        var: customer_details_results

    - name: Place a new order
      ansible.builtin.uri:
        url: "{{ base_url }}/place_order"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body: "{{ item }}"
      loop:
        - { customer_id: "customer_id_1", medicine: "medicine_A", quantity: 5 }
        - { customer_id: "customer_id_2", medicine: "medicine_B", quantity: 3 }
        - { customer_id: "customer_id_1", medicine: "medicine_B", quantity: 2 }

    - name: Get orders
      ansible.builtin.uri:
        url: "{{ base_url }}/view_orders"
        method: GET
      register: orders_results

    - name: Display orders results
      ansible.builtin.debug:
        var: orders_results
