= Moving from the manual approach to one more automated

Up to this point our approach has been implemented manually, every single step takes time and the only way to repeat the process is to repeat it completely. This is of course not the most efficient way to do this. However we can make use of Containerfiles to automate the process.

To containerize each microservice, you can create a `Containerfile` for each service:

== Inventory Containerfile

.Containerfile_inventory_service
[source,dockerfile]
----
FROM fedora
RUN dnf install -yqq python3 pip
RUN pip install Flask
COPY inventory_service.py .
CMD ["python3", "inventory_service.py"]
----

== Order Containerfile

.Containerfile_order_service
[source,dockerfile]
----
FROM fedora
RUN dnf install -yqq python3 pip
RUN pip install Flask
COPY order_service.py .
CMD ["python3", "order_service.py"]
----

== Customer Containerfile

.Containerfile_customer_service
[source,dockerfile]
----
FROM fedora
RUN dnf install -yqq python3 pip
RUN pip install Flask
COPY customer_service.py .
CMD ["python3", "customer_service.py"]
----

== Billing Containerfile

.Containerfile_billing_service
[source,dockerfile]
----
FROM fedora
RUN dnf install -yqq python3 pip
RUN pip install Flask
COPY billing_service.py .
CMD ["python3", "billing_service.py"]
----

Notice that each of the Containerfiles follows the same steps as we did when creating the containers manually, install dependencies, copy the source code and run the service.

To build these images, navigate to the directory containing each service's Containerfile and run the following command:

[source,shell]
----
$ podman build -t inventory-service -f Containerfile_inventory_service .
$ podman build -t order-service -f Containerfile_order_service .
$ podman build -t customer-service -f Containerfile_customer_service .
$ podman build -t billing-service -f Containerfile_billing_service .
----

Notice, we are no longer tagging our images as `manual` because they are being created automatically. 

[source,shell]
----
$ podman images
REPOSITORY                         TAG         IMAGE ID      CREATED         SIZE
localhost/billing-service          latest      d5f2a420aba5  19 seconds ago  480 MB
localhost/customer-service         latest      3744e51347f2  24 seconds ago  480 MB
localhost/order-service            latest      1ae01d6ddef5  42 seconds ago  480 MB
localhost/inventory-service        latest      8a043ac8b906  59 seconds ago  480 MB
----

Did, you noticed how fast the building process was? Since images are built in layers the repetitive layers do not have to be processed twice and therefore the repetitive steps are skipped.

Once ready we can execute our container as follows:

[source,shell]
----
$ podman run --rm --name inventory_service --network host -d localhost/inventory-service
$ podman run --rm --name order_service --network host -d localhost/order-service 
$ podman run --rm --name customer_service --network host -d localhost/customer-service 
$ podman run --rm --name billing_service --network host -d localhost/billing-service
----

Let's test a service to be sure is working

[source,shell]
----
$ curl http://0.0.0.0:5001/view_inventory
{"inventory":{"medicine_A":{"price":10,"stock":100},"medicine_B":{"price":15,"stock":50}}}
----

To combine all the individual Containerfiles into a single Containerfile, you can use a multi-stage build to reduce duplication. Here's how you can structure it:

.Containerfiles_multi_staged
[source,dockerfile]
----
# Multi-stage build for a combined Containerfile

# Base image
FROM fedora as base

# Install common dependencies on the "base"
RUN dnf install -yqq python3 pip
RUN pip install Flask

# Inventory Service stage
FROM base as inventory_service
LABEL service=inventory
COPY inventory_service.py .
CMD ["python3", "inventory_service.py"]

# Order Service stage
FROM base as order_service
LABEL service=order
COPY order_service.py .
CMD ["python3", "order_service.py"]

# Customer Service stage
FROM base as customer_service
LABEL service=customer
COPY customer_service.py .
CMD ["python3", "customer_service.py"]

# Billing Service stage
FROM base as billing_service
LABEL service=billing
COPY billing_service.py .
CMD ["python3", "billing_service.py"]
----

To build this image, run the following command:

[source,shell]
----
$ podman build -t combined-services -f Containerfiles_multi_staged .
----

When we look at the recently created images we see that the base image is named as requested but the rest of the images do not receive a name which is why we had to use the `LABEL` command so we can differentiate between the images.

[source,shell]
----
$ podman images
REPOSITORY                         TAG         IMAGE ID      CREATED             SIZE
localhost/combined-services        latest      47ea6019e36f  About a minute ago  480 MB
<none>                             <none>      d5f2a420aba5  25 minutes ago      480 MB
<none>                             <none>      3744e51347f2  25 minutes ago      480 MB
<none>                             <none>      1ae01d6ddef5  26 minutes ago      480 MB
<none>                             <none>      8a043ac8b906  26 minutes ago      480 MB
----

The `--label service=inventory` flag filters containers based on the specified label, ensuring that only containers with the matching label are considered.

Keep in mind that labels are more commonly used for organizational purposes, versioning, and other metadata-related tasks rather than for directly controlling the execution of containers. 

But wait! Just like we did in the manual procedure we created a single image to run all the containers, why don't we do the same here?

.Containerfile
[source,dockerfile]
----
FROM fedora
RUN dnf install -yqq python3 pip
RUN pip install Flask
COPY *.py .
ENTRYPOINT ["python3"]
----

Notice we have changed our image slightly to copy all the source code files and change the `CMD` for an `ENTRYPOINT` that will allow us to use the `CMD` or `Command` at runtime to selectively run an specific python script that will be taken as an argument, as follows:

First we build the image:

[source,shell]
----
$ podman build -t pharmacy:v2 .
----

Notice, that since we called the Containerfile exactly Containerfile there is no need to specify the file name at build time

Now we run the containers:

[source,shell]
----
$ podman run --rm --name inventory_service --network host -d localhost/pharmacy:v2 inventory_service.py
$ podman run --rm --name order_service --network host -d localhost/pharmacy:v2 order_service.py
$ podman run --rm --name customer_service --network host -d localhost/pharmacy:v2 customer_service.py
$ podman run --rm --name billing_service --network host -d localhost/pharmacy:v2 billing_service.py
----

Let's test a service to be sure is working

[source,shell]
----
$ curl http://0.0.0.0:5001/view_inventory
{"inventory":{"medicine_A":{"price":10,"stock":100},"medicine_B":{"price":15,"stock":50}}}
----
