= Making our data persistent

What if we modify the `order_service.py` source code to store the orders in a file as persistent storage?

.order_service.py
[source, python]
----
from flask import Flask, jsonify, request
import json
import os

app = Flask(__name__)

# File to store orders
ORDERS_FILE = '/data/orders.json'

# Create the orders file if it doesn't exist
if not os.path.exists(ORDERS_FILE):
    with open(ORDERS_FILE, 'w') as f:
        json.dump([], f)

# Function to read orders from the file
def read_orders():
    with open(ORDERS_FILE, 'r') as f:
        return json.load(f)

# Function to write orders to the file
def write_orders(orders):
    with open(ORDERS_FILE, 'w') as f:
        json.dump(orders, f, indent=2)

# Endpoint to place orders
@app.route('/place_order', methods=['POST'])
def place_order():
    order_details = request.json
    medicine_name = order_details['medicine']
    requested_quantity = order_details['quantity']

    # Prepare order details
    order = {
        'customer_id': order_details['customer_id'],
        'medicine': medicine_name,
        'quantity': requested_quantity,
        'status': 'Pending'
    }

    # Read existing orders from the file
    orders = read_orders()

    # Append the new order
    orders.append(order)

    # Write updated orders back to the file
    write_orders(orders)

    return jsonify({'message': 'Order placed successfully', 'order_details': order}), 201

# Endpoint to view orders
@app.route('/view_orders', methods=['GET'])
def view_orders():
    # Read orders from the file and return
    orders = read_orders()
    return jsonify({'orders': orders}), 200

if __name__ == '__main__':
    app.run(port=5002)
----

In this version:

- The `ORDERS_FILE` constant is defined to specify the filename for storing orders and we are using `/data/orders.json` as our default database.
- Two functions (read_orders and write_orders) are introduced to read and write orders to the file.
- Before processing orders, the application reads existing orders from the file and updates it accordingly.

This way, your orders are persisted across server restarts, making the application more resilient to restarts and downtime.

Since we have a new version of code we need to re-build the images and create new containers:


First we build the image:

[source,shell]
----
$ podman build -t pharmacy:v3 .
----

Notice, we now tagged the image as `v3` to differentiate it from the existing image.

Now we run the containers but since only the `order_service` was modified let's stop just that one and run it again using the new version:

[source,shell]
----
$ podman stop order_service
$ podman run --rm --name order_service --network host -d localhost/pharmacy:v3 order_service.py
----

Wait! something is wrong! let's investigate:

1. Run the containers without the `--rm` option to avoid losing the traces of the execution.

[source,shell]
----
$ podman run --name order_service --network host -d localhost/pharmacy:v3 order_service.py
----

We can now see the container is in exited status

[source,shell]
----
$ podman ps -a | grep order_service
4ced8fd4668b  localhost/pharmacy:v3               order_service.py      17 seconds ago  Exited (1) 18 seconds ago                order_service
----

Let's find out why?

[source,shell]
----
$ podman logs order_service
Traceback (most recent call last):
  File "//order_service.py", line 12, in <module>
    with open(ORDERS_FILE, 'w') as f:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/data/orders.json'
----

Ah! the problem is that when we execute the Python script it is unable to find the '/data/orders.json' file which is suppose to be created automatically but not the `/data` directory so we need to add the `/data` directory to our image by modifying our Containerfile

.Containerfile
[source,dockerfile]
----
FROM fedora
RUN dnf install -yqq python3 pip
RUN pip install Flask
RUN mkdir /data
COPY *.py .
ENTRYPOINT ["python3"]
----

Once again, build the image. This time version 4:

[source,shell]
----
$ podman build -t pharmacy:v4 .
----

Ensure you don't have another container already in the system with the same name:

[source,shell]
----
$ podman rm order_service
----

And run the container for the `order_service` using version four:

[source,shell]
----
$ podman run --rm --name order_service --network host -d localhost/pharmacy:v4 order_service.py
----

Let's test a service to be sure is working

[source,shell]
----
$ curl http://127.0.0.1:5002/view_orders
{"orders":[]}
----

Let's add one order and then check the file to see if it is saved

[source,shell]
----
$ curl -X POST \
    -H "Content-Type: application/json" \
    -d '{"customer_id": "customer_id_1", "medicine": "medicine_A", "quantity": 5}' \
    http://localhost:5002/place_order

{"message":"Order placed successfully","order_details":{"customer_id":"customer_id_1","medicine":"medicine_A","quantity":5,"status":"Pending"}}
----

We can print our active orders:

[source,shell]
----
$ curl http://127.0.0.1:5002/view_orders
{"orders":[{"customer_id":"customer_id_1","medicine":"medicine_A","quantity":5,"status":"Pending"}]}
----

And we check the file:

[source,shell]
----
$ podman exec -ti order_service cat /data/orders.json
[
  {
    "customer_id": "customer_id_1",
    "medicine": "medicine_A",
    "quantity": 5,
    "status": "Pending"
  }
]
----

Great! now we are storing the orders in the database but if we stop the container for whatever reason we will loose all the information so we need to convert the `/data` folder into a volume to make it permanent

Which is a simple as:

[source,shell]
----
$ podman volume create data
$ podman volume inspect data | grep Mountpoint
          "Mountpoint": "/home/jmedinar/.local/share/containers/storage/volumes/data/_data",
----

Now we can run our container again but using our volume:

[source,shell]
----
$ podman stop order_service
$ podman run --rm --name order_service --network host -v data:/data:rw -d localhost/pharmacy:v4 order_service.py
# OR
$ podman run --rm --name order_service --network host --mount type=volume,src=data,dst=/data,rw=true -d localhost/pharmacy:v4 order_service.py
----

Let's add one order

[source,shell]
----
$ curl -X POST \
    -H "Content-Type: application/json" \
    -d '{"customer_id": "customer_id_1", "medicine": "medicine_A", "quantity": 5}' \
    http://localhost:5002/place_order

{"message":"Order placed successfully","order_details":{"customer_id":"customer_id_1","medicine":"medicine_A","quantity":5,"status":"Pending"}}
----

Now let's check our database file but instead of doing it thru the file in the container lets do it through the local file in the host.

[source,shell]
----
$ cat /home/jmedinar/.local/share/containers/storage/volumes/data/_data/orders.json
[
  {
    "customer_id": "customer_id_1",
    "medicine": "medicine_A",
    "quantity": 5,
    "status": "Pending"
  }
]
----

Excellent!, If our container is stopped we can just restart it and the data will persist. 

== Isolate the application

Until now we have been using the `host` network when running the containers to remove the isolation between containers and use the host network avoiding having to deal with ports and other network related configurations.

This time let's use a different approach. Let's create a network specifically for our application so it can work in isolation from the hosts but not from the components of the application itself.

Let's create a network:

[source,shell]
----
$ podman network create pharmacy
$ podman network inspect pharmacy
----

Now since the source code of our application currently tries to use the host network and Flask is binding to localhost (127.0.0.1) by default and therefore it will only be reachable from within the container or a container within the same subnet. But want to reach it from the local machine (host), so we need Flask to bind to all IP's:

So we will change the line on each python script as follows:

[source,python]
----
# On billing_service.py
    app.run(host='0.0.0.0',port=5004)
# On customer_service.py
    app.run(host='0.0.0.0',port=5003)
# On order_service.py
    app.run(host='0.0.0.0',port=5002)
# On inventory_service.py
    app.run(host='0.0.0.0',port=5001)
----

Let's build the Version 5 of our application

[source,shell]
----
$ podman build -t pharmacy:v5 .
----

Let's now create the containers using the latest version:

[source,shell]
----
$ podman run --rm --name inventory_service --network pharmacy -p 5001:5001 -d localhost/pharmacy:v5 inventory_service.py
$ podman run --rm --name customer_service --network pharmacy -p 5003:5003  -d localhost/pharmacy:v5 customer_service.py
$ podman run --rm --name billing_service --network pharmacy -p 5004:5004  -d localhost/pharmacy:v5 billing_service.py
$ podman run --rm --name order_service --network pharmacy -v data:/data:rw -p 5002:5002  -d localhost/pharmacy:v5 order_service.py
----

Let's try to print our active orders:

[source,shell]
----
$ curl http://0.0.0.0:5002/view_orders
{"orders":[{"customer_id":"customer_id_1","medicine":"medicine_A","quantity":5,"status":"Pending"}]}
----

Excellent, now we have a fully isolated application running on its own network with persistent storage and a fully functional application.
