---
- name: Testing the pharmacy application
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    base_url: "http://127.0.0.1:"
    inventory: "5001/view_inventory"
    order_place: "5002/place_order"
    order_view: "5002/view_orders"
    customer: "5003/view_customer"

  tasks:

    - name: Check inventory
      ansible.builtin.uri:
        url: "{{ base_url }}{{ inventory }}"
        method: GET
        return_content: true
      register: inventory_results

    - name: Display inventory results
      ansible.builtin.debug:
        var: inventory_results

    - name: Get customer details
      ansible.builtin.uri:
        url: "{{ base_url }}{{ customer }}/{{ item }}"
        method: GET
        return_content: true
      register: customer_details_results
      loop:
        - customer_id_1
        - customer_id_2

    - name: Display customer details results
      ansible.builtin.debug:
        var: customer_details_results

    - name: Place a new order
      ansible.builtin.uri:
        url: "{{ base_url }}{{ order_place }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body: "{{ item }}"
        return_content: true
      loop:
        - { customer_id: "customer_id_1", medicine: "medicine_A", quantity: 5 }
        - { customer_id: "customer_id_2", medicine: "medicine_B", quantity: 3 }
        - { customer_id: "customer_id_1", medicine: "medicine_B", quantity: 2 }

    - name: Get orders
      ansible.builtin.uri:
        url: "{{ base_url }}{{ order_view }}"
        method: GET
        return_content: true
      register: orders_results

    - name: Display orders results
      ansible.builtin.debug:
        var: orders_results
